// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgvofuttzqgalwnphyfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNndm9mdXR0enFnYWx3bnBoeWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzc0MTEsImV4cCI6MjA2MTY1MzQxMX0.5bGDfvaEWiHzHEOXGY3Hv6ztAUZuLEChyJZSP2Zq7-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);